# Generated by Django 4.2.23 on 2025-08-13 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('balance', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('DEPOSIT', 'Пополнение'), ('WITHDRAW', 'Снятие')], editable=False, verbose_name='Тип операции')),
                ('amount', models.PositiveBigIntegerField(editable=False, verbose_name='Величина')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
