# Generated by Django 4.2.23 on 2025-08-15 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name='Величина'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('DEPOSIT', 'Пополнение'), ('WITHDRAW', 'Снятие')], verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='wallets.wallet'),
        ),
    ]
