# Generated by Django 4.2.23 on 2025-08-15 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_operation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Величина'),
        ),
    ]
